# osmrender style sheet
# Colors are R,G,B or R,G,B,A with alpha from 0 to 255.

background = 242,239,232

water.fill = 154,196,214,230
water.line = 94,151,183,255
water.width = 2

waterway.line = 92,158,194,255
waterway.width = 2

forest.fill = 176,205,165,190
forest.line = 134,168,121,255
forest.width = 1

park.fill = 190,218,170,185
park.line = 142,181,119,255
park.width = 1

building.fill = 217,203,184,175
building.line = 157,138,117,255
building.width = 1

motorway.casing = 196,126,92,220
motorway.casing_width = 7
motorway.line = 238,171,105,255
motorway.width = 5

primary.casing = 202,145,98,220
primary.casing_width = 6
primary.line = 246,194,118,255
primary.width = 4

secondary.casing = 198,176,121,220
secondary.casing_width = 5
secondary.line = 246,226,148,255
secondary.width = 3

minor_road.casing = 190,182,169,220
minor_road.casing_width = 4
minor_road.line = 250,248,240,255
minor_road.width = 2

path.line = 147,139,122,255
path.width = 1

rail.casing = 222,218,210,220
rail.casing_width = 3
rail.line = 92,91,101,255
rail.width = 1